micronaut:
  application:
    name: maliketh
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/maliketh
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    dialect: POSTGRES
    username: maliketh
    password: maliketh
netty:
  default:
    allocator:
      max-order: 3
