spring:
  profiles:
    active: local
  mustache:
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5432/maliketh
    username: maliketh
    password: maliketh
    datasource:
      driver-class-name: org.postgresql.Driver
