spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: >
        jdbc:postgresql://localhost:5432/maliketh
      pool-name: maliketh-pool
      username: maliketh
      password: maliketh

logging:
  level:
    in.stonecolddev: DEBUG
    org.springframework.jdbc.core: TRACE

cms:
  pageSize: 10
cache:
  entryCacheExpireAfterWrite: 1 # in minutes
  entryCountCacheExpire: 1 # in minutes
  cacheMaxSize: 10_000
pebble:
  suffix: .html
