spring:
  config:
    activate:
      on-profile: local-docker
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: >
        jdbc:postgresql://172.29.113.38:5432/maliketh
      pool-name: maliketh-pool
      username: maliketh
      password: maliketh

logging:
  level:
    in.stonecolddev: DEBUG
    org.springframework.jdbc.core: TRACE